---
# file: installZabbixAgent.yml
- hosts: all
  strategy: free
  connection: local
  gather_facts: false
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: winrm
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to host"
- hosts: running_hosts
  strategy: free
  any_errors_fatal: false
  gather_facts: false
  ignore_errors: yes
  serial:
   - 1
   - 5%
   - 25%
  max_fail_percentage: 25%


  tasks:
  - name: Stop Zabbix agent service
    win_service:
      name: Zabbix Agent
      state: stopped
  - name: Check if installation files are there
    win_stat:
      path: 'C:\Zabbix\zabbix_agentd.exe'
    register: stat_file
  - name: Create Zabbix directory
    win_file:
     path: 'C:\Zabbix'
     state: directory
  - name: Download agent executable
    win_get_url:
      url: http://10.15.4.36/zabbix/bin/zabbix_agentd.exe
      dest: c:\Zabbix\zabbix_agentd.exe
      force: True
    when: stat_file.stat.exists == False
  - name: Download agent config file
    win_get_url:
      url: http://10.15.4.36/zabbix/conf/zabbix_agentd.conf
      dest: c:\Zabbix\zabbix_agentd.conf
      force: True
  - name: Remove Zabbix agent service
    win_service:
      name: Zabbix Agent
      state: absent
  - name: Check if config files are downloaded
    win_stat:
      path: 'C:\Zabbix\zabbix_agentd.conf'
    register: conf_file
  - name: Create Zabbix agent service
    raw: 'C:\Zabbix\zabbix_agentd.exe --config C:\Zabbix\zabbix_agentd.conf --install'
    when: conf_file.stat.exists == True
  - name: Create firewall rule to allow Zabbix port 10050
    win_firewall_rule:
      name: Zabbix agent
      program: C:\Zabbix\zabbix_agentd.exe
      action: allow
      direction: in
      protocol: tcp
      profiles: domain,private,public
      state: present
      enabled: yes
  - name: Start Zabbix agent service
    win_service:
      name: Zabbix Agent
      state: restarted
      start_mode: delayed
