---
# file: installCarbonBlack.yml
- hosts: all
  strategy: free
  connection: local
  gather_facts: false
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: winrm
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to host"
- hosts: running_hosts
  strategy: free
  any_errors_fatal: false
  gather_facts: false
  ignore_errors: yes
  serial:
   - 1
   - 5%
   - 25%
  max_fail_percentage: 25%
  tasks:
  - name: Remove Old AnyDesk
    win_package:
      path: 'http://oyautiv01.oya.internal/repo/Inlight_IT_Support_OYA.msi'
      product_id: '{75E08D97-60C3-402B-A586-21E5CA047B2E}'
      state: absent
      log_path: c:\temp\AD_install_{{lookup('pipe', 'date +%Y%m%d')}}.log
  - name: Start AnyDesk Client installation
    win_package:
      path: 'http://oyautiv01.oya.internal/repo/Inlight_IT_Support_OYA_2021.05.11.msi'
      creates_path: 'C:\Program Files (x86)\AnyDesk-5754769e_msi\AnyDesk-5754769e_msi.exe'
      creates_version: 6.2.3.0
      state: present
      log_path: c:\temp\AD_install_{{lookup('pipe', 'date +%Y%m%d')}}.log
  - name: Download Icon File
    win_get_url: 
      url: 'http://oyautiv01.oya.internal/repo/InlightIT-small-logo.ico'
      dest: 'C:\Program Files (x86)\AnyDesk-5754769e_msi\InlightIT-small-logo.ico'

  - name: Create an application shortcut on the desktop
    community.windows.win_shortcut:
      src: 'C:\Program Files (x86)\AnyDesk-5754769e_msi\AnyDesk-5754769e_msi.exe'
      dest: C:\Users\Public\Desktop\My IT Support.lnk
      icon: 'C:\Program Files (x86)\AnyDesk-5754769e_msi\InlightIT-small-logo.ico'