---
# file: installCarbonBlack.yml
- hosts: all
  strategy: free
  connection: local
  gather_facts: false
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: winrm
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to host"
- hosts: running_hosts
  strategy: free
  any_errors_fatal: false
  gather_facts: false
  ignore_errors: yes
  serial:
   - 1
   - 5%
   - 25%
  max_fail_percentage: 25%
  tasks:
  - name: Start CB sensor installation
    win_package:
      path: 'http://oyautiv01.oya.internal/repo/installer_vista_win7_win8-64-3.6.0.2076.msi'
      arguments:
        - COMPANY_CODE=297YG62YW301Q!BX3#N3
        - CLI_USERS=S-1-5-21-3842904660-1982940162-3626352813-512
      creates_path: 'C:\Program Files\Confer\RepMgr.exe'
      creates_version: 3.6.0.2076
      state: present
      log_path: c:\temp\CB_install_{{lookup('pipe', 'date +%Y%m%d')}}.log
      
