---
# file: updatereboot.yml
- hosts: all
  strategy: free
  connection: local
  gather_facts: false
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: winrm
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to host"
- hosts: running_hosts
  ignore_unreachable: yes
  strategy: free
  any_errors_fatal: false
  gather_facts: false
  ignore_errors: yes
  serial:
   - 1
   - 5%
   - 25%
  max_fail_percentage: 25%
  vars:
    win_updates_categories:
      - Updates
      - Upgrades
      - Critical Updates
      - Security Updates
      - Update Rollups
      - Definition Updates
      - Drivers
  tasks:
  # Remove Windows Defender
  - name: Remove Windows Defender
    win_feature:
      name: Windows-Defender
      state: absent
      include_sub_features: yes
      include_management_tools: yes
    register: win_defender
    ignore_errors: yes

  - name: Reboot if needed
    win_reboot:
      reboot_timeout: 3600
      post_reboot_delay: 120
    when: win_defender.reboot_required
    ignore_errors: yes


  # Check if there are missing updates
  - name: Check for missing updates.
    win_updates:
      state: searched
      category_names: "{{ win_updates_categories }}"
    register: update_count
    ignore_errors: yes

  - name: Reboot if needed
    win_reboot:
      reboot_timeout: 3600
      post_reboot_delay: 120
    when: update_count.reboot_required
    ignore_errors: yes

  - name: Install missing updates.
    win_updates:
      category_names: "{{ win_updates_categories }}"
    register: update_result

  - name: Reboot if needed
    win_reboot:
      reboot_timeout: 3600
      pre_reboot_delay: 120
    when: update_result.reboot_required
    ignore_errors: yes