---
# file: UpgradeFromMicrosoft.yml
- hosts: all
  strategy: free
  connection: local
  gather_facts: false
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: winrm
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to host"
- hosts: running_hosts
  #strategy: free
  any_errors_fatal: false
  gather_facts: true
  ignore_errors: yes
  ignore_unreachable: yes
  tasks:
  - name: Create Self Public IP Variable
    raw: 'Resolve-DnsName -Name {{ hostvars[inventory_hostname].ansible_fqdn }} -Type A -DnsOnly | select -expand IPAddress'
    register: windows_public_ip
  - debug: msg="{{ windows_public_ip.stdout_lines | join }}"
  - name: Create folders
    win_file:
      path: C:\_Windows_FU\packages
      state: directory
  - name: download psexec
    win_get_url:
      url: https://download.sysinternals.com/files/PSTools.zip
      dest: C:\_Windows_FU\packages\PSTools.zip
  - name: unzip psexec
    win_unzip:
      src: C:\_Windows_FU\packages\PSTools.zip
      dest: C:\_Windows_FU\packages\pstools
      delete_archive: yes
  - name: Download executable
    win_get_url:
      url: https://go.microsoft.com/fwlink/?LinkID=799445
      dest: C:\_Windows_FU\packages\Win10Upgrade.exe
  - name: Put some details into log file
    win_copy:
      content:
        "{{ hostvars[inventory_hostname].ansible_fqdn }}
        {{ windows_public_ip.stdout_lines | join }}"
      dest:
        C:\temp\WindowsUpgrade_{{ hostvars[inventory_hostname].ansible_fqdn }}.txt
  - name: Save version info before upgrading
    win_shell: |
      "`nBuild number before:`n" +(Get-CimInstance Win32_OperatingSystem).BuildNumber >> C:\temp\WindowsUpgrade_{{ hostvars[inventory_hostname].ansible_fqdn }}.txt
  - name: Notify users 5 minutes before restart
    raw: Msg /server:{{ hostvars[inventory_hostname].ansible_fqdn }}/ * Message "PC restart in 5min. Please save your work. You will be logged off in 5 minutes."
  - name: Wait for 5 minutes and reboot host
    win_reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 300
      post_reboot_delay: 120
      test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  - name: Start Upgrading
    win_psexec: 
      command: C:\_Windows_FU\packages\Win10Upgrade.exe /quietinstall /skipeula /auto upgrade
      elevated: yes
      interactive: yes
      executable: C:\_Windows_FU\packages\pstools\psexec.exe
  - name: Wait for poweroff
    local_action:
      module: shell
      cmd: "ping -c 1 {{ windows_public_ip.stdout_lines | join }}"
    register: myping
    failed_when: (myping.rc != 0) and ('100% packet loss' not in myping.stdout)
    retries: 720
    delay: 10
    until: myping.rc == 1
  - name: Wait 2 hours, but only start checking after 2 minutes
    wait_for_connection:
      delay: 120
      timeout: 7200
  - name: Wait 5 minutes
    pause:
      minutes: 5
  - name: Save version info after upgrading
    win_shell: |
      "`nBuild number after:`n" +(Get-CimInstance Win32_OperatingSystem).BuildNumber >> C:\temp\WindowsUpgrade_{{ hostvars[inventory_hostname].ansible_fqdn }}.txt
  - name: copy log file
    win_copy:
      src: C:\temp\WindowsUpgrade_{{ hostvars[inventory_hostname].ansible_fqdn }}.txt
      dest: \\test-win10\ANS
      remote_src: yes
