---
# file: UpgradeFromMicrosoft.yml
- hosts: all
  strategy: free
  connection: local
  gather_facts: false
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: winrm
        - name: add devices with connectivity to the "running_hosts" group
          group_by:
            key: "running_hosts"
      rescue:
        - debug: msg="cannot connect to host"
- hosts: running_hosts
  #strategy: free
  any_errors_fatal: false
  gather_facts: true
  ignore_errors: yes
  ignore_unreachable: yes
  tasks:
  - name: Create folders
    win_file:
      path: C:\_Windows_FU\packages
      state: directory
  - name: Download executable
    win_get_url:
      url: https://go.microsoft.com/fwlink/?LinkID=799445
      dest: C:\_Windows_FU\packages\Win10Upgrade.exe
  - name: Save version info before upgrading
    win_shell: Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name ReleaseID -ErrorAction Stop | Out-File -FilePath C:\temp\WindowsUpgrade.txt -Append
  - debug: msg="{{ ansible_facts['all_ipv4_addresses [1]'] }}"
  - name: Wait for poweroff
    local_action:
      module: shell
      cmd: "ping -c 1 {{ ansible_all_ipv4_addresses [1] }}"
    register: myping
    failed_when: (myping.rc != 0) and ('100% packet loss' not in myping.stdout)
    retries: 500
    delay: 10
    until: myping.rc == 1
  - name: Wait 5 minute
    pause:
      minutes: 5
  - name: Reboot host and wait for it to restart
    win_reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 90
      test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  - name: Wait 5 minute
    pause:
      minutes: 5
  - name: Start Upgrading
    win_shell: Start-Process -FilePath C:\_Windows_FU\packages\Win10Upgrade.exe -ArgumentList '/quietinstall /skipeula /auto upgrade'
  - name: Wait for poweroff
    local_action:
      module: shell
      cmd: "ping -c 1 {{ ansible_all_ipv4_addresses [1] }}"
    register: myping
    failed_when: (myping.rc != 0) and ('100% packet loss' not in myping.stdout)
    retries: 500
    delay: 10
    until: myping.rc == 1
  - name: Wait 20 minutes, but only start checking after 2 minutes
    wait_for_connection:
      delay: 120
      timeout: 1200
  - name: Wait 1 minute
    pause:
      minutes: 1
  - name: Save version info after upgrading
    win_shell: Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -Name ReleaseID -ErrorAction Stop | Out-File -FilePath C:\temp\WindowsUpgrade.txt -Append
